/**
 * 统一存放 action 常量
 */
export const HAMSTER = {
    BLOCK_ADD: 'BLOCK_ADD',
    // BLOCK_ACTIVATE: 'BLOCK_ACTIVATE',
    // BLOCK_CNACEL_ACTIVE: 'BLOCK_CANCEL_ACTIVE',
    // BLOCK_RE_ACTIVE: 'BLOCK_RE_ACTIVE_',
    BLOCK_PROPS_CHANGE: 'BLOCK_PROPS_CHANGE',
    ENTITIES_PROPS_CHANGE: 'ENTITIES_PROPS_CHANGE',
    BLOCK_CLICK: 'BLOCK_CLICK',
    BLOCK_UNITE: 'BLOCK_UNITE'
};
